export interface ApprovalsPopupResponse {
  UserName: string;
  StartDateTime: string;
  EndDateTime: string;
  Client: string;
  Project: string;
  Process: string;
  TotalHours: string;
}

export interface List {
  SubmissionId: number;
  WorkitemId: any;
  TaskName: string;
  EmpolyeeId: number;
  EmpolyeeName: string;
  Role: string;
  EstimateTime: number;
  TotalTime: number;
  ClientId: number;
  ClientName: string;
  ProjectId: number;
  ProjectName: string;
  ProcessId: number;
  ParentProcess: string | null;
  SubProcessId: number;
  SubProcess: string;
  WorkTypeId: number;
  WorkType: string;
  StatusId: number;
  StatusType: string;
  StatusName: string;
  ColorCode: string;
  TaskColorCode: string;
  TaskStatusName: string;
  PriorityId: number | null;
  PriorityName: string | null;
  AssigneeId: number;
  AssignedName: string;
  StartDate: string;
  EndDate: string;
  Quantity: number | null;
  EmployeeIsManual: boolean;
  ReviewerIsManual: boolean | null;
  State: number;
  Timer: number;
  EmployeeManualTime: number | null;
  ManagerId: number;
  ManagerName: string;
  TimelogId: number | null;
  IsActive: boolean;
  IsFinalSubmited: boolean;
  IsHasErrorlog: boolean;
  IsHasErrorlogAddedByClient: boolean;
  ErrorlogSignedOffPending: boolean;
  ReviewerId: number;
  ReviewerName: string;
  StdTimeSec: number;
  StdTime: string;
  PreparorTimeSec: number;
  PreparorTime: string;
  ReviewerTimeSec: number;
  ReviewerTime: string;
  ActualTimeSec: number;
  ActualTime: string;
  ReviewDate: string | null;
  ReviewerEditedTimeSec: number;
  ReviewerEditedTime: string;
  TotalEditedTimeSec: number;
  TotalEditedTime: string;
  QAId: number | null;
  QAName: string | null;
  QATimeSec: number | null;
  QATime: string;
  QAEditedTimeSec: number | null;
  QAEditedTime: string;
  QAQuantity: number | null;
}

export interface InitialFilterApprovals {
  PageNo: number;
  PageSize: number;
  sortColumn: string;
  isDesc: boolean;
  globalSearch: string;
  userId: number | null;
  ClientId: number | null;
  IsShowAll: number | null;
  DepartmentId: number | null;
  TypeOfWork: number | null;
  ProjectId: number | null;
  projectId: number | null;
  StatusId: number | null;
  ProcessId: number | null;
  startDate: string | null | undefined;
  endDate: string | null | undefined;
  startDateReview: string | null | undefined;
  endDateReview: string | null | undefined;
  dueDate: string | null | undefined;
  DateFilter: string | null | undefined;
}

export interface ApprovalsActionBarData {
  selectedRowsCount: number;
  selectedRowIds: number[] | [];
  selectedWorkItemIds: number[];
  selectedRowClientId: number[] | [];
  selectedRowWorkTypeId: number[] | [];
  settingSelectedId: () => void;
  id: number;
  workitemId: number;
  onEdit: (rowId: number, Id: number, iconIndex?: number) => void;
  onComment: (rowData: boolean, selectedId: number) => void;
  reviewList: List[] | [];
  getReviewList: () => void;
  getInitialPagePerRows: () => void;
  handleClearSelection: () => void;
  getOverLay?: (e: boolean) => void;
  activeTab: number;
}
