//Enum for save filter type

export const client = 4;
export const project = 5;
export const user = 6;
export const timesheet = 7;
export const workload = 8;
export const userlog = 9;
export const audit = 10;
export const billingReport = 11;
export const customReport = 12;
export const AdminRatingsReports = 13;
export const logReport = 14;
export const activityReport = 15;
export const apReport = 16;
export const amReport = 17;
export const kraReport = 18;
export const clientReport = 4;
export const wltrReport = 19;
